### PR TITLE
Add support to use mdoc

### LINKED ISSUE #292: Change tut for mdoc
Any thoughts about changing tut for mdoc. Anyone already looking at it?

### PR DESCRIPTION
**Pull request by rafaparadela**
This PR closes #292 

What it does basically is:

- [x] Adds a new sbt setting `micrositeCompilingDocsTool` to chose between `tut` and `mdoc`.
- [x] Edits the task `makeMicrosite` to run either `makeTut` or `makeMdoc` according to the value of `micrositeCompilingDocsTool`.
- [x] Adds the `sbt-mdoc` pluging.
- [x] Adds a scripted test to prove the compilation of mdoc snippets
- [x] Adds a scripted test to prove how `makeMicrosite` ends without effects when the `micrositeCompilingDocsTool` has an invalid value.
- [x] Updates the documentation to explain how operate with both options and a detailed guide for migrating from `tut` to `mdoc`.

### CODE REVIEW

**Comment by rafaparadela** [comment]
@juanpedromoreno It seems that Travis gives us a red in the `0.13` version as we discussed yesterday.

**Comment by juanpedromoreno** [comment]
@rafaparadela I'll try to have a look at this today. Thanks.

**Comment by MaureenElsberry** [comment]
@rafaparadela done reviewing the docs, only made tiny changes. Thanks!

**Comment by rafaparadela** [comment]
Thanks a lot @MaureenElsberry

**Pull request merged**
