### PR TITLE
Revert "Revert "New style redesign""

### PR DESCRIPTION
**Pull request by AntonioMateoGomez**
Reopen "New style redesign" PR in order to fix travis build

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
@AntonioMateoGomez  Is this ready to go? 🚀

**Comment by calvellido** [comment]
Yes it is, we didn't merged in case you wanted to have a version release before 1.0.0 (based on this https://github.com/47deg/sbt-microsites/pull/355#issuecomment-549465038)

**Comment by juanpedromoreno** [comment]
Thanks @calvellido for pointing it out. I've just commented on that PR, presently we have other breaking changes that I think we want to deliver altogether in 1.0.0. Does it make sense?

**Comment by calvellido** [comment]
Definitely @juanpedromoreno, looking forward to the release of sbt-microsites 1.0.0!

**Pull request merged**
