### PR TITLE
Adds usage in the wild and includes cats as first lib

### PR DESCRIPTION
**Pull request by raulraja**
@justinelsberry @MaureenElsberry Can you please review?
I'll wait for some of the cats folks to give the go ahead before merging this.

### CODE REVIEW

**Comment by non** [comment]
I'm happy for Cats to be linked here. Thanks for making this great tool! 👍

**Comment by justinelsberry** [comment]
@raulraja can we add all of our internal libraries as well?

**Comment by tpolecat** [comment]
Feel free to add https://tpolecat.github.io/tuco/ and https://tpolecat.github.io/atto/ if you want to, but don't feel obligated. They're both weird.

**Comment by raulraja** [comment]
@justinelsberry We need to update Fetch, Github4s and others to the latest version so the linked images don't break first. We'll add those in a separate PR. I'll make sure the entire org is aware and updates the README.

**Pull request merged**
