### PR TITLE
Fix #76: Improve table style

### LINKED ISSUE #76: table formatting is slightly wack
The default styling doesn't paint borders around tables, which makes them slightly strange looking.

image

What I would really like I think is an option that makes formatting _exactly_ like what GH does, if that's an easy thing to do (no idea).

### PR DESCRIPTION
**Pull request by jvican**
À la GitHub.

It slightly improves how tables are styled. I'm no web designer, so
bear with me with my poor CSS style.
microsite

### CODE REVIEW

**Comment by jvican** [comment]
CI is broken.

**Comment by jvican** [comment]
ping @raulraja ?

**Comment by juanpedromoreno** [comment]
Thanks for your contribution @jvican ! 

does this PR fix https://github.com/47deg/sbt-microsites/issues/76 ?

**Comment by juanpedromoreno** [comment]
LGTM btw :)

**Comment by jvican** [comment]
Yes, it does @juanpedromoreno. Has this been released in the snapshot?

**Comment by juanpedromoreno** [comment]
Yep, still `0.3.1-SNAPSHOT`

Thanks again!

**Pull request merged**
